#!/bin/bash

ROOTPATH="$( cd "$(dirname "$0")" ; pwd -P )/.."
NEWSPATH=$ROOTPATH/pages/news

rm -f $NEWSPATH/*

tags=$(grep 'tags:' $ROOTPATH/_posts/*.md | sed 's/^.*: //' | sed 's/[,\[]//g' |  sed 's/\]//g' )

unique=$(echo -e "${tags// /\\n}" | sort -u)

for tag in $unique; do
    echo $tag
    echo "---
title: News
tagName: $tag
search: exclude
permalink: news/$tag.html
layout: default
hide: true
---
{% include taglogic.html %}
" > $NEWSPATH/$tag.html
done
